import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import Ajv from 'ajv';
import { apply, initialState, projectApplication, actions } from '../skills/woia-re-rental-application/scripts/application.mjs';
import { digest } from '../skills/woia-re-rental-application/scripts/guard.mjs';
const payload={property_id:'property-1',terms_ref:'terms-1',participants:[{subject_id:'applicant-1',participant_role:'applicant'},{subject_id:'guarantor-1',participant_role:'guarantor'}],field_values:[{subject_id:'applicant-1',field:'income',value:'synthetic-evidence-reference'}]};
function request(action='rental-application.create',p=payload,target='application-1') {
  return { organization:'org-1',action,target,purpose:'rental-review',now:'2026-10-07T12:00:00Z',operation_id:'operation-1',expected_revision:0,payload:structuredClone(p),participant_scope:['applicant-1','guarantor-1'],field_scope:['income','evidence_links','status','decisions'],authority:{department:'leasing',authenticated:true,organization:'org-1',actor:'agent-1',purpose:'rental-review',policy_revision:'policy-1',current:true,valid_from:'2026-10-07T00:00:00Z',valid_until:'2026-10-08T00:00:00Z',actions,resources:['application-1','guarantee-1','applicant-1','guarantor-1','property-1','terms-1','doc-1','doc-version-1','reason-1'],participants:['applicant-1','guarantor-1'],fields:['participants','property_id','terms_ref','income','evidence_links','status','decisions','coverage']},evidence:{source:'form-1',reference:'evidence-1',version:'1',recorded_at:'2026-10-07T11:00:00Z',fresh_until:'2026-10-08T00:00:00Z',fact_kind:'rental-application'},source_authority:{organization:'org-1',map_revision:'map-1',writer:'woia-re-rental-application',source:'form-1',fact_kinds:['rental-application'],targets:[target],current:true,valid_from:'2026-10-07T00:00:00Z',valid_until:'2026-10-08T00:00:00Z'}};
}
function next(state,action,p,target='application-1') { const r=request(action,p,target);r.expected_revision=state.revision;r.operation_id=`operation-${state.revision+1}`;return r; }
function approve(r) { r.human_decision={principal:'human-1',kind:'competent-human',organization:r.organization,action:r.action,target:r.target,payload_digest:digest(r.payload),policy_revision:'policy-1',current:true,reference:'approval-1',valid_from:'2026-10-07T00:00:00Z',valid_until:'2026-10-08T00:00:00Z'};return r; }
const created=()=>apply(initialState('org-1'),request()).state;
test('create does not infer acceptance from supplied applicant fields',()=> { const s=created(); assert.equal(s.applications['application-1'].status,'DRAFT');assert.deepEqual(s.applications['application-1'].decisions,[]); });
for(const [label,change,code] of [
 ['missing grant',r=>delete r.authority,/DEPARTMENT/],['revoked',r=>r.authority.revoked=true,/CURRENT_AUTHORITY/],['hold',r=>r.authority.hold=true,/CURRENT_AUTHORITY/],['stop',r=>r.authority.emergency_stop=true,/CURRENT_AUTHORITY/],['purpose',r=>r.purpose='other',/CURRENT_AUTHORITY/],['organization',r=>r.organization='org-other',/ORGANIZATION/],['action',r=>r.authority.actions=[],/ACTION_OR_RESOURCE/],['expired',r=>r.now='2026-10-09T00:00:00Z',/CURRENT_AUTHORITY/],['source conflict',r=>r.source_authority.conflict=true,/SCOPED_SOURCE/],['future source map',r=>r.source_authority.valid_from='2026-10-08T00:00:00Z',/SCOPED_SOURCE/],['wrong writer',r=>r.source_authority.writer='crm',/SCOPED_SOURCE/],['stale source',r=>r.evidence.fresh_until='2026-10-06T00:00:00Z',/SCOPED_SOURCE/],['participant access',r=>r.authority.participants=['applicant-1'],/PARTICIPANT_ACCESS/],['field access',r=>r.authority.fields=['participants'],/FIELD_ACCESS/],['duplicate participant',r=>r.payload.participants.push(r.payload.participants[0]),/DUPLICATE/],['foreign field participant',r=>r.payload.field_values[0].subject_id='foreign',/FIELD_PARTICIPANT/],['unowned finance',r=>r.payload.payment=true,/UNOWNED_FIELDS/],['revision conflict',r=>r.expected_revision=9,/REVISION/]
]) test(label,()=> {const s=initialState('org-1'),r=request();change(r);assert.throws(()=>apply(s,r),code);assert.equal(s.revision,0);});
test('idempotent replay requires current grants and exact material payload',()=>{const r=request(),s=apply(initialState('org-1'),r).state;assert.equal(apply(s,r).state.revision,1);r.payload.terms_ref='other';assert.throws(()=>apply(s,r),/IDEMPOTENCY_CONFLICT/);});
test('update creates version, preserves previous value and denies foreign field scope',()=> {let s=created();let r=next(s,'rental-application.update',{field_values:[{subject_id:'applicant-1',field:'income',value:'new-ref'}]});r.field_scope=[];assert.throws(()=>apply(s,r),/REQUEST_FIELD/);r.field_scope=['income'];s=apply(s,r).state;assert.equal(s.applications['application-1'].version,2);assert.equal(s.applications['application-1'].versions[0].field_values[0].value,'synthetic-evidence-reference');});
test('evidence nary subject/document/version/purpose is preserved',()=> {let s=created();const p={subject_id:'guarantor-1',document_id:'doc-1',document_version_id:'doc-version-1',evidence_purpose:'guarantee-proof'};s=apply(s,next(s,'rental-application.evidence.link',p)).state;assert.deepEqual(s.applications['application-1'].evidence_links[0],p);assert.equal(s.applications['application-1'].status,'DRAFT');});
test('submit is not acceptance; competent exact decision required',()=>{let s=created();s=apply(s,next(s,'rental-application.submit',{})).state;assert.equal(s.applications['application-1'].status,'SUBMITTED');const r=next(s,'rental-application.decision.record',{decision:'ACCEPTED',application_version:1,reason_ref:'reason-1'});assert.throws(()=>apply(s,r),/HUMAN_DECISION/);approve(r);const accepted=apply(s,r).state;assert.equal(accepted.applications['application-1'].decisions[0].decision,'ACCEPTED');assert.equal(accepted.applications['application-1'].status,'SUBMITTED');r.payload.decision='REJECTED';assert.throws(()=>apply(s,r),/HUMAN_DECISION/);});
test('guarantee nary coverage is distinct from participant role and accepted only by competent decision',()=>{let s=created();const p={application_id:'application-1',participants:[{subject_id:'guarantor-1',participant_role:'guarantor'}],coverage:[{property_id:'property-1',obligation_scope_code:'rent',coverage_scope_id:'scope-1',terms_ref:'terms-1'}],status:'PROPOSED'};s=apply(s,next(s,'guarantee.create',p,'guarantee-1')).state;assert.equal(s.guarantees['guarantee-1'].coverage.length,1);const r=next(s,'guarantee.update',{...p,status:'ACCEPTED'},'guarantee-1');assert.throws(()=>apply(s,r),/HUMAN/);s=apply(s,approve(r)).state;assert.equal(s.guarantees['guarantee-1'].version,2);assert.equal(s.guarantees['guarantee-1'].versions[0].status,'PROPOSED');});
test('projection checks access before retrieval and filters both axes',()=>{let loaded=0;const r=request();r.authority.participants=[];assert.throws(()=>projectApplication(()=>{loaded++;return created().applications['application-1'];},r),/PARTICIPANT/);assert.equal(loaded,0);r.authority.participants=['applicant-1','guarantor-1'];r.participant_scope=['guarantor-1'];assert.deepEqual(projectApplication(()=>created().applications['application-1'],r),[]);});
test('department scope is not broadened by generic grant',()=>{const r=request();r.authority.department='finance';assert.throws(()=>apply(initialState('org-1'),r),/DEPARTMENT/);});
test('Customer Service intake does not grant competent acceptance',()=>{let s=created();s=apply(s,next(s,'rental-application.submit',{})).state;const r=approve(next(s,'rental-application.decision.record',{decision:'ACCEPTED',application_version:1,reason_ref:'reason-1'}));r.authority.department='customer-service';assert.throws(()=>apply(s,r),/COMPETENT_OWNER/);});
test('schema binds payload to exact operation',()=>{const schema=JSON.parse(readFileSync(new URL('../skills/woia-re-rental-application/schemas/command.schema.json',import.meta.url)));const validate=new Ajv({strict:false}).compile(schema);const r=request();assert.equal(validate(r),true);r.action='rental-application.submit';assert.equal(validate(r),false);r.payload={};assert.equal(validate(r),true);});
